# Generated by Django 5.2.8 on 2026-06-01 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_strategyconversation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_input', models.TextField()),
                ('conversation_history', models.JSONField(default=list)),
                ('model_output', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('clarify', 'Clarify'), ('failed', 'Failed'), ('non_strategy', 'Non Strategy')], default='complete', max_length=20)),
                ('errors', models.JSONField(default=list)),
                ('turns_taken', models.IntegerField(default=1)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('missing_field', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
