# Generated by Django 5.2.8 on 2026-06-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customindicator'),
        ('api', '0004_strategyquerylog'),
    ]

    operations = [
    ]
