# Generated by Django 5.2.8 on 2026-07-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyquerylog',
            name='edited_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='strategyquerylog',
            name='ran_backtest',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
