# Generated by Django 5.2.8 on 2026-07-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_strategyquerylog_edited_fields_and_more'),
        ('api', '0008_userprofile_usagecounter'),
    ]

    operations = [
    ]
