# Generated by Django 5.2.8 on 2026-07-13 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20260709_1944'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('strategy_assistant', 'Strategy Assistant'), ('indicator_assistant', 'Indicator Assistant'), ('nl_parse', 'NL Strategy Parse'), ('nl_chat', 'NL Strategy Chat'), ('other', 'Other')], default='other', max_length=32)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('context_text', models.TextField(blank=True, default='')),
                ('messages', models.JSONField(blank=True, default=list)),
                ('request_meta', models.JSONField(blank=True, default=dict)),
                ('response_text', models.TextField(blank=True, default='')),
                ('response_meta', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('user_rating', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='plans_page', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='backtestrun',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='dsl_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='dsl_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='usagecounter',
            name='period',
            field=models.CharField(max_length=16),
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['user', 'created_at'], name='api_backtes_user_id_79afbf_idx'),
        ),
        migrations.AddField(
            model_name='aiinteractionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbacklead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiinteractionlog',
            index=models.Index(fields=['kind', 'created_at'], name='api_aiinter_kind_0e5e51_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinteractionlog',
            index=models.Index(fields=['user', 'created_at'], name='api_aiinter_user_id_4e0657_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacklead',
            index=models.Index(fields=['email', 'created_at'], name='api_feedbac_email_ea8ef7_idx'),
        ),
    ]
