# Generated by Django 5.2.8 on 2026-07-13 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_aiinteractionlog_feedbacklead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=16)),
                ('algorithm', models.CharField(blank=True, default='', max_length=32)),
                ('strategy_name', models.CharField(blank=True, default='', max_length=255)),
                ('input_dsl', models.JSONField(blank=True, null=True)),
                ('parameter_space', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('best_params', models.JSONField(blank=True, null=True)),
                ('best_dsl', models.JSONField(blank=True, null=True)),
                ('best_result', models.JSONField(blank=True, null=True)),
                ('top_results', models.JSONField(blank=True, default=list)),
                ('total_runs', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimization_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_optimiz_user_id_e4844e_idx'), models.Index(fields=['method', 'created_at'], name='api_optimiz_method_fba966_idx')],
            },
        ),
    ]
