# Generated by Django 5.2.8 on 2026-07-16 20:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userprofile_email_verified_emailverificationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_id', models.CharField(max_length=36)),
                ('session_id', models.CharField(max_length=36)),
                ('path', models.CharField(max_length=200)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='api_pagevie_created_772519_idx'), models.Index(fields=['anon_id', 'created_at'], name='api_pagevie_anon_id_6b788a_idx'), models.Index(fields=['session_id', 'created_at'], name='api_pagevie_session_e23f4a_idx')],
            },
        ),
    ]
