"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import warnings
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent


def load_env_file(env_path: Path) -> None:
    """Load KEY=VALUE pairs into process env without overriding existing vars."""
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue

        if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
            value = value[1:-1]

        os.environ.setdefault(key, value)


# Support either backend/.env or project-root .env
load_env_file(BASE_DIR / ".env")
load_env_file(PROJECT_ROOT / ".env")

# macOS python.org builds don't wire system CA certs into OpenSSL, which breaks
# TLS verification (e.g. SMTP to Resend). Point Python's default SSL context at
# certifi's CA bundle unless the environment already provides one.
try:
    import certifi

    os.environ.setdefault("SSL_CERT_FILE", certifi.where())
except ImportError:
    pass


def env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name: str, default: int, minimum: int | None = None) -> int:
    value = os.getenv(name)
    if value is None:
        parsed = default
    else:
        try:
            parsed = int(value)
        except ValueError:
            parsed = default
    if minimum is not None and parsed < minimum:
        return minimum
    return parsed


def env_float(name: str, default: float, minimum: float | None = None) -> float:
    value = os.getenv(name)
    if value is None:
        parsed = default
    else:
        try:
            parsed = float(value)
        except ValueError:
            parsed = default
    if minimum is not None and parsed < minimum:
        return minimum
    return parsed


def env_list(name: str, default: list[str] | None = None) -> list[str]:
    value = os.getenv(name)
    if value is None:
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False so a forgotten DEBUG env var in production fails safe (no
# tracebacks/settings leak). Local development sets DEBUG=true in .env.
DEBUG = env_bool("DEBUG", False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-development-only-change-me"
    else:
        warnings.warn(
            "DJANGO_SECRET_KEY is not set with DEBUG=False. "
            "Using an ephemeral key; set DJANGO_SECRET_KEY in deployment.",
            RuntimeWarning,
        )
        SECRET_KEY = os.urandom(48).hex()

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    ["127.0.0.1", "localhost", "[::1]"] if DEBUG else [],
)
if not ALLOWED_HOSTS and not DEBUG:
    warnings.warn(
        "ALLOWED_HOSTS is empty with DEBUG=False. Falling back to localhost-only.",
        RuntimeWarning,
    )
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", "[::1]"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'api',
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Serve static files with WhiteNoise in production (right after SecurityMiddleware).
# Guarded so local dev without whitenoise installed still boots.
try:
    import whitenoise  # noqa: F401

    MIDDLEWARE.insert(
        MIDDLEWARE.index('django.middleware.security.SecurityMiddleware') + 1,
        'whitenoise.middleware.WhiteNoiseMiddleware',
    )
    _WHITENOISE_AVAILABLE = True
except ImportError:
    _WHITENOISE_AVAILABLE = False

_default_local_origins = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://192.168.1.169:8080",
]
CORS_ALLOWED_ORIGINS = [*env_list("CORS_ALLOWED_ORIGINS", _default_local_origins if DEBUG else [])]
if DEBUG:
    # Keep common local origins available in development, even if .env overrides CORS list.
    CORS_ALLOWED_ORIGINS = list(dict.fromkeys([*CORS_ALLOWED_ORIGINS, *_default_local_origins]))
if not CORS_ALLOWED_ORIGINS and not DEBUG:
    warnings.warn(
        "CORS_ALLOWED_ORIGINS is empty with DEBUG=False. Falling back to localhost-only origins.",
        RuntimeWarning,
    )
    CORS_ALLOWED_ORIGINS = list(_default_local_origins)
CORS_ALLOW_CREDENTIALS = False
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", CORS_ALLOWED_ORIGINS if DEBUG else [])
if DEBUG:
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys([*CSRF_TRUSTED_ORIGINS, *CORS_ALLOWED_ORIGINS]))
if not CSRF_TRUSTED_ORIGINS and not DEBUG:
    CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Security hardening (kept dev-friendly via DEBUG defaults).
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_HSTS_SECONDS = env_int("SECURE_HSTS_SECONDS", 0 if DEBUG else 31536000, minimum=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", not DEBUG)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", not DEBUG)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# In production (Railway sets DATABASE_URL) switch to Postgres via dj-database-url.
# Local dev has no DATABASE_URL, so it keeps SQLite and doesn't need the package.
_database_url = os.getenv("DATABASE_URL")
if _database_url:
    try:
        import dj_database_url

        DATABASES["default"] = dj_database_url.parse(
            _database_url,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    except ImportError:
        warnings.warn(
            "DATABASE_URL is set but dj-database-url is not installed; "
            "falling back to SQLite.",
            RuntimeWarning,
        )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# When WhiteNoise is installed (production), serve compressed + hashed static
# files. Django 5.2 uses STORAGES (the old STATICFILES_STORAGE is deprecated).
if _WHITENOISE_AVAILABLE:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# API protection and abuse limits.
# Number of trusted reverse proxies in front of the app. 0 (default) = none, so
# rate limiting uses the real socket peer and ignores the spoofable
# X-Forwarded-For header. Behind Railway/Vercel's edge set this to 1 so the real
# client IP (appended by the trusted proxy) is used instead of REMOTE_ADDR.
TRUSTED_PROXY_COUNT = env_int("TRUSTED_PROXY_COUNT", 0, minimum=0)
MAX_JSON_BODY_BYTES = env_int("MAX_JSON_BODY_BYTES", 1048576, minimum=1)
MAX_DSL_TEXT_LENGTH = env_int("MAX_DSL_TEXT_LENGTH", 50000, minimum=1000)
MAX_INITIAL_BALANCE = env_float("MAX_INITIAL_BALANCE", 100000000.0, minimum=1.0)
ASYNC_JOB_TTL_SECONDS = env_int("ASYNC_JOB_TTL_SECONDS", 3600, minimum=60)
ASYNC_JOB_MAX_ENTRIES = env_int("ASYNC_JOB_MAX_ENTRIES", 500, minimum=20)
ASYNC_JOB_MAX_PER_USER = env_int("ASYNC_JOB_MAX_PER_USER", 3, minimum=1)
API_RATE_LIMITS = {
    "auth": {
        "max_requests": env_int("RATE_LIMIT_AUTH_MAX_REQUESTS", 20, minimum=1),
        "window_seconds": env_int("RATE_LIMIT_AUTH_WINDOW_SECONDS", 300, minimum=1),
    },
    # Optimizer job starts + indicator sandbox runs share this bucket.
    "compute": {
        "max_requests": env_int("RATE_LIMIT_COMPUTE_MAX_REQUESTS", 20, minimum=1),
        "window_seconds": env_int("RATE_LIMIT_COMPUTE_WINDOW_SECONDS", 60, minimum=1),
    },
    "backtest": {
        "max_requests": env_int("RATE_LIMIT_BACKTEST_MAX_REQUESTS", 60, minimum=1),
        "window_seconds": env_int("RATE_LIMIT_BACKTEST_WINDOW_SECONDS", 60, minimum=1),
    },
    # Job-status polling: must comfortably cover several optimizers polling
    # at once (3 concurrent pollers at 1s each = 180/min).
    "status": {
        "max_requests": env_int("RATE_LIMIT_STATUS_MAX_REQUESTS", 240, minimum=1),
        "window_seconds": env_int("RATE_LIMIT_STATUS_WINDOW_SECONDS", 60, minimum=1),
    },
    "assistant": {
        "max_requests": env_int("RATE_LIMIT_ASSISTANT_MAX_REQUESTS", 30, minimum=1),
        "window_seconds": env_int("RATE_LIMIT_ASSISTANT_WINDOW_SECONDS", 60, minimum=1),
    },
    "general": {
        "max_requests": env_int("RATE_LIMIT_GENERAL_MAX_REQUESTS", 180, minimum=1),
        "window_seconds": env_int("RATE_LIMIT_GENERAL_WINDOW_SECONDS", 60, minimum=1),
    },
}

# Strategy assistant provider. Use local Ollama by default during development.
# Set ORCA_ASSISTANT_PROVIDER=openai and ORCA_ASSISTANT_MODEL to a fine-tuned
# model id when the proprietary hosted model is ready.
ORCA_ASSISTANT_PROVIDER = os.getenv("ORCA_ASSISTANT_PROVIDER", "ollama")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_API_BASE_URL = os.getenv("OPENAI_API_BASE_URL", "https://api.openai.com/v1")
ORCA_ASSISTANT_MODEL = os.getenv("ORCA_ASSISTANT_MODEL", "gpt-5.1")
ORCA_ASSISTANT_OLLAMA_BASE_URL = os.getenv("ORCA_ASSISTANT_OLLAMA_BASE_URL", "http://127.0.0.1:11434")
ORCA_ASSISTANT_OLLAMA_MODEL = os.getenv("ORCA_ASSISTANT_OLLAMA_MODEL", "gemma3:4b")  # strategy advisor
ORCA_INDICATOR_ASSISTANT_OLLAMA_MODEL = os.getenv("ORCA_INDICATOR_ASSISTANT_OLLAMA_MODEL", "qwen2.5-coder:7b")
# Local inference is much slower than a hosted API — especially a "cold" request
# where Ollama has to load the model back into memory first (it unloads idle
# models after ORCA_ASSISTANT_OLLAMA_KEEP_ALIVE). Give it a separate, longer
# budget than the hosted-provider timeout below so a slow-but-fine local
# response isn't mistaken for a hung service.
ORCA_ASSISTANT_OLLAMA_TIMEOUT_SECONDS = env_float("ORCA_ASSISTANT_OLLAMA_TIMEOUT_SECONDS", 120.0, minimum=1.0)
# How long Ollama keeps the model loaded in memory after the last request
# (Ollama's own default is "5m"). Keeping it resident across a chat session
# avoids paying the multi-second "cold load" cost on every message.
ORCA_ASSISTANT_OLLAMA_KEEP_ALIVE = os.getenv("ORCA_ASSISTANT_OLLAMA_KEEP_ALIVE", "30m")
ORCA_ASSISTANT_TIMEOUT_SECONDS = env_float("ORCA_ASSISTANT_TIMEOUT_SECONDS", 30.0, minimum=1.0)
ORCA_ASSISTANT_TEMPERATURE = env_float("ORCA_ASSISTANT_TEMPERATURE", 0.2, minimum=0.0)
ORCA_ASSISTANT_MAX_OUTPUT_TOKENS = env_int("ORCA_ASSISTANT_MAX_OUTPUT_TOKENS", 900, minimum=100)
ORCA_ASSISTANT_MAX_MESSAGE_CHARS = env_int("ORCA_ASSISTANT_MAX_MESSAGE_CHARS", 4000, minimum=200)
ORCA_ASSISTANT_MAX_CONTEXT_CHARS = env_int("ORCA_ASSISTANT_MAX_CONTEXT_CHARS", 20000, minimum=1000)
ORCA_ASSISTANT_MAX_HISTORY_MESSAGES = env_int("ORCA_ASSISTANT_MAX_HISTORY_MESSAGES", 16, minimum=1)
ORCA_ASSISTANT_STORE_RESPONSES = env_bool("ORCA_ASSISTANT_STORE_RESPONSES", False)
ORCA_ASSISTANT_MARKET_DATA_DIR = os.getenv(
    "ORCA_ASSISTANT_MARKET_DATA_DIR",
    str(BASE_DIR / "core" / "data_csvs"),
)
ORCA_ASSISTANT_MARKET_DATA_MAX_TICKERS = env_int("ORCA_ASSISTANT_MARKET_DATA_MAX_TICKERS", 3, minimum=1)
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "")

# Email — defaults to console backend for local dev so no SMTP setup is needed.
# In production set EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# and supply EMAIL_HOST / EMAIL_HOST_USER / EMAIL_HOST_PASSWORD / EMAIL_PORT.
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@orca.app")
# Used to build the password-reset link inserted in the email.
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ]
}

# Rate limiting and async-job state live in the cache, so it must be shared
# across worker processes/instances. Set REDIS_URL in any multi-instance
# deployment; the file-based fallback is only shared between workers on a single
# host (and its location is configurable via FILE_CACHE_LOCATION).
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.environ["REDIS_URL"],
    }
    if os.environ.get("REDIS_URL") else {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": os.getenv("FILE_CACHE_LOCATION", "/tmp/orca_cache"),
    }
}
