import { useMemo } from "react";
import { Helmet } from "react-helmet-async";
import { Link, useParams, Navigate } from "react-router-dom";
import { ArrowLeft, FileText, Shield, AlertTriangle } from "lucide-react";
import { useAuth } from "@/context/AuthContext";
import orcaLogo from "@/assets/orca-logo.png";

const COMPANY = "Orca";
const CONTACT_EMAIL = "support@orca.app";
const EFFECTIVE_DATE = "June 13, 2026";

type Section = { heading: string; body: string[] };
type LegalDoc = {
  slug: string;
  title: string;
  icon: typeof FileText;
  intro: string;
  sections: Section[];
};

const RISK: LegalDoc = {
  slug: "risk",
  title: "Risk Disclosure",
  icon: AlertTriangle,
  intro:
    "Please read this disclosure carefully before relying on anything you see in Orca. By using the platform you confirm that you understand and accept these risks.",
  sections: [
    {
      heading: "Not financial advice",
      body: [
        `${COMPANY} is a research, backtesting, and educational tool. Nothing in the platform — including strategies, indicators, AI-generated suggestions, backtest results, optimizer output, or paper-trading simulations — constitutes financial, investment, tax, or legal advice, or a recommendation to buy, sell, or hold any security or financial instrument.`,
        `You are solely responsible for your own trading and investment decisions. You should consult a licensed financial professional before making any investment.`,
      ],
    },
    {
      heading: "Hypothetical and simulated results",
      body: [
        "Backtested, optimized, and paper-traded results are hypothetical. They are generated by applying rules to historical data and do not represent real trades placed in live markets.",
        "Hypothetical performance has many inherent limitations. It benefits from hindsight, may not account for real-world factors such as liquidity, slippage, fees, financing costs, or the emotional discipline required to follow a strategy, and is frequently subject to over-fitting. No representation is made that any account will or is likely to achieve profits or losses similar to those shown.",
      ],
    },
    {
      heading: "Past performance is not indicative of future results",
      body: [
        "Markets change. A strategy that performed well on historical data may perform poorly, or lose money, in the future. Past performance — real or hypothetical — is never a guarantee of future returns.",
      ],
    },
    {
      heading: "Trading involves substantial risk of loss",
      body: [
        "Trading and investing in financial markets carry a substantial risk of loss and are not suitable for every investor. You may lose some or all of your invested capital. Only risk capital you can afford to lose should ever be used for trading.",
      ],
    },
    {
      heading: "Market data",
      body: [
        "Market data shown in Orca may be delayed, incomplete, or contain errors, and is provided on an \"as is\" basis for research purposes only. It should not be relied upon for live trading or order execution.",
      ],
    },
    {
      heading: "No liability",
      body: [
        `To the maximum extent permitted by law, ${COMPANY} and its operators accept no liability for any loss or damage arising from your use of, or reliance on, the platform or any output it produces.`,
      ],
    },
  ],
};

const TERMS: LegalDoc = {
  slug: "terms",
  title: "Terms of Service",
  icon: FileText,
  intro: `These Terms of Service ("Terms") govern your access to and use of ${COMPANY}. By creating an account or using the platform, you agree to these Terms.`,
  sections: [
    {
      heading: "1. Eligibility & accounts",
      body: [
        "You must be at least 18 years old and able to form a binding contract to use Orca. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.",
      ],
    },
    {
      heading: "2. Research tool, not advice",
      body: [
        `${COMPANY} is provided for research, backtesting, and educational purposes only and does not provide financial advice. See our Risk Disclosure for important details about hypothetical results and trading risk.`,
      ],
    },
    {
      heading: "3. Acceptable use",
      body: [
        "You agree not to misuse the platform, including by attempting to disrupt or compromise its security, reverse-engineering non-public components, scraping at scale, reselling access without authorization, or using it for unlawful purposes.",
      ],
    },
    {
      heading: "4. Your content",
      body: [
        "You retain ownership of the strategies, indicators, and configurations you create. You grant us a limited license to store and process this content solely to operate and improve the service.",
      ],
    },
    {
      heading: "5. Subscriptions & billing",
      body: [
        "Paid plans, where offered, are billed in advance on a recurring basis and renew automatically until cancelled. Fees are non-refundable except where required by law. We may change pricing with reasonable advance notice.",
      ],
    },
    {
      heading: "6. Availability & changes",
      body: [
        "We strive for high availability but do not guarantee uninterrupted access. We may modify, suspend, or discontinue features at any time. Market data and third-party services may be unavailable from time to time.",
      ],
    },
    {
      heading: "7. Disclaimer of warranties",
      body: [
        'The platform is provided "as is" and "as available" without warranties of any kind, express or implied, including merchantability, fitness for a particular purpose, and non-infringement.',
      ],
    },
    {
      heading: "8. Limitation of liability",
      body: [
        `To the maximum extent permitted by law, ${COMPANY} will not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any trading or investment losses, arising from your use of the platform.`,
      ],
    },
    {
      heading: "9. Termination",
      body: [
        "You may stop using the service at any time. We may suspend or terminate access for violations of these Terms. Provisions that by their nature should survive termination will survive.",
      ],
    },
    {
      heading: "10. Contact",
      body: [`Questions about these Terms can be sent to ${CONTACT_EMAIL}.`],
    },
  ],
};

const PRIVACY: LegalDoc = {
  slug: "privacy",
  title: "Privacy Policy",
  icon: Shield,
  intro: `This Privacy Policy explains what information ${COMPANY} collects, how we use it, and the choices you have.`,
  sections: [
    {
      heading: "Information we collect",
      body: [
        "Account information you provide, such as your name and email address.",
        "Content you create, such as saved strategies, custom indicators, backtest runs, and paper-trading workspaces.",
        "Usage and technical data, such as log data and basic device information, used to operate and secure the service.",
      ],
    },
    {
      heading: "How we use your information",
      body: [
        "To provide, maintain, and improve the platform; to authenticate you; to communicate important service information; and to protect against fraud and abuse.",
      ],
    },
    {
      heading: "Third-party services",
      body: [
        "We use third parties to deliver the service, which may include authentication providers (e.g. Google sign-in), market data providers, hosting, and — where enabled — payment processors. These providers process data only as needed to perform their function.",
      ],
    },
    {
      heading: "Data retention",
      body: [
        "We retain your information for as long as your account is active or as needed to provide the service. You may request deletion of your account and associated data.",
      ],
    },
    {
      heading: "Security",
      body: [
        "We use reasonable technical and organizational measures to protect your data. No method of transmission or storage is completely secure, and we cannot guarantee absolute security.",
      ],
    },
    {
      heading: "Your rights",
      body: [
        `Depending on your location, you may have rights to access, correct, export, or delete your personal data. To exercise these rights, contact ${CONTACT_EMAIL}.`,
      ],
    },
    {
      heading: "Contact",
      body: [`Privacy questions can be sent to ${CONTACT_EMAIL}.`],
    },
  ],
};

const DOCS: Record<string, LegalDoc> = {
  risk: RISK,
  terms: TERMS,
  privacy: PRIVACY,
};

const Legal = () => {
  const { doc } = useParams<{ doc: string }>();
  const legal = useMemo(() => (doc ? DOCS[doc] : undefined), [doc]);
  const { user } = useAuth();
  const homeHref = user ? "/dashboard" : "/";

  if (!legal) {
    return <Navigate to="/legal/terms" replace />;
  }

  const Icon = legal.icon;

  return (
    <>
      <Helmet>
        <title>{`${legal.title} - ${COMPANY}`}</title>
        <meta name="description" content={`${legal.title} for ${COMPANY}.`} />
      </Helmet>

      <div className="min-h-screen bg-background">
        <header className="border-b border-border/50">
          <div className="container mx-auto flex items-center justify-between px-4 py-4">
            <Link to={homeHref} className="flex items-center gap-2">
              <img src={orcaLogo} alt="Orca Logo" className="h-8 w-8 rounded-lg" />
              <span className="text-lg font-bold tracking-tight">{COMPANY}</span>
            </Link>
            <Link
              to={homeHref}
              className="flex items-center gap-1.5 text-sm text-muted-foreground transition-colors hover:text-foreground"
            >
              <ArrowLeft className="h-4 w-4" />
              {user ? "Back to dashboard" : "Back to home"}
            </Link>
          </div>
        </header>

        <main className="container mx-auto max-w-3xl px-4 py-12">
          <div className="mb-8 flex items-center gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl border border-primary/25 bg-primary/10">
              <Icon className="h-5 w-5 text-primary" />
            </div>
            <div>
              <h1 className="text-2xl font-bold tracking-tight">{legal.title}</h1>
              <p className="text-xs text-muted-foreground">Effective {EFFECTIVE_DATE}</p>
            </div>
          </div>

          <div className="mb-8 rounded-lg border border-border bg-card/50 p-4 text-sm text-muted-foreground">
            {legal.intro}
          </div>

          <div className="space-y-8">
            {legal.sections.map((section) => (
              <section key={section.heading}>
                <h2 className="mb-2 text-lg font-semibold">{section.heading}</h2>
                <div className="space-y-3">
                  {section.body.map((paragraph, index) => (
                    <p key={index} className="text-sm leading-relaxed text-muted-foreground">
                      {paragraph}
                    </p>
                  ))}
                </div>
              </section>
            ))}
          </div>

          <div className="mt-12 flex flex-wrap gap-4 border-t border-border/50 pt-6 text-sm">
            <Link to="/legal/terms" className="text-muted-foreground hover:text-foreground">
              Terms of Service
            </Link>
            <Link to="/legal/privacy" className="text-muted-foreground hover:text-foreground">
              Privacy Policy
            </Link>
            <Link to="/legal/risk" className="text-muted-foreground hover:text-foreground">
              Risk Disclosure
            </Link>
          </div>

          <p className="mt-8 text-xs text-muted-foreground/70">
            This document is a general template and not legal advice. Have it reviewed by qualified
            counsel for your jurisdiction before relying on it commercially.
          </p>
        </main>
      </div>
    </>
  );
};

export default Legal;
